services:
  # Главный сервис
  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-ewm-main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ewm-main-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - CLIENT_URL=http://stats-server:9090

  # База для main-service
  postgres-ewm-main-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "5433:5432" # проброс на хост, если нужен доступ снаружи
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm -d ewm"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Сервис статистики
  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - postgres-ewm-stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ewm-stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1488

  # База для stats-server
  postgres-ewm-stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1488
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
